### ISSUE TITLE
Support for standard .vue files

### ISSUE THREAD

**Issue by armaldio** [dleitee/crates#3]
I've tried to generate files from a standard vue file 

```vue
<template></template>

<script>
	import T from 'crates'
	
	export default {
		name      : 'installer',
		mounted() {
			console.log(T("Hello world"));
		}
	}
</script>

<style></style>
```
I get the following error:
```log
compiling file:src/renderer/App.vueParser: { SyntaxError: Adjacent JSX elements must be wrapped in an enclosing tag (12:0)
    at Parser.pp$5.raise (D:\Projects\ConstructAddonInstaller\Installer\node_modules\babylon\lib\index.js:4454:13)
    at Parser.pp$9.jsxParseElementAt (D:\Projects\ConstructAddonInstaller\Installer\node_modules\babylon\lib\index.js:7213:10)
    at Parser.pp$9.jsxParseElement (D:\Projects\ConstructAddonInstaller\Installer\node_modules\babylon\lib\index.js:7224:15)
    at Parser.parseExprAtom (D:\Projects\ConstructAddonInstaller\Installer\node_modules\babylon\lib\index.js:7236:21)
    at Parser.pp$3.parseExprSubscripts (D:\Projects\ConstructAddonInstaller\Installer\node_modules\babylon\lib\index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (D:\Projects\ConstructAddonInstaller\Installer\node_modules\babylon\lib\index.js:3474:19)
    at Parser.pp$3.parseExprOps (D:\Projects\ConstructAddonInstaller\Installer\node_modules\babylon\lib\index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (D:\Projects\ConstructAddonInstaller\Installer\node_modules\babylon\lib\index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (D:\Projects\ConstructAddonInstaller\Installer\node_modules\babylon\lib\index.js:3344:19)
    at Parser.parseMaybeAssign (D:\Projects\ConstructAddonInstaller\Installer\node_modules\babylon\lib\index.js:6433:24)
    at Parser.pp$3.parseExpression (D:\Projects\ConstructAddonInstaller\Installer\node_modules\babylon\lib\index.js:3306:19)
    at Parser.pp$1.parseStatement (D:\Projects\ConstructAddonInstaller\Installer\node_modules\babylon\lib\index.js:1906:19)
    at Parser.parseStatement (D:\Projects\ConstructAddonInstaller\Installer\node_modules\babylon\lib\index.js:5910:22)
    at Parser.pp$1.parseBlockBody (D:\Projects\ConstructAddonInstaller\Installer\node_modules\babylon\lib\index.js:2268:21)
    at Parser.pp$1.parseTopLevel (D:\Projects\ConstructAddonInstaller\Installer\node_modules\babylon\lib\index.js:1778:8)
    at Parser.parse (D:\Projects\ConstructAddonInstaller\Installer\node_modules\babylon\lib\index.js:1673:17) pos: 223, loc: Position { line: 12, column: 0 } }
```

**Comment by dleitee** [comment]
Ok, I have to test it here.

**Comment by nop33** [comment]
Is there an update on this issue? :)

**Comment by dleitee** [comment]
Nope, I can't test it yet.

**Comment by nop33** [comment]
With the proper guidance in the codebase, I could help with this issue. Let me know if I can help somehow.

**Comment by dleitee** [comment]
Sure @nop33, can you open a (work in progress) PR? and we'll discuss the implementation.

What do you think?
